repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.941
    hooks:
      - id: mypy
        exclude: '.*tests/.*|.*docs/.*'
        args: [--no-strict-optional, --ignore-missing-imports, --follow-imports=silent]
        additional_dependencies: [types-all]
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.8
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
  - repo: .
    rev: v2.7.9
    hooks:
    - id: export-requirements-docs
